version: '3'

services:

  app:
    container_name: album_manager
    build: .
    ports:
      - 8000:8000
    restart: on-failure
  #  environment:
  #    PORT: 8080
  #    DB_CONN: "postgres://user:password@db:5432/db?sslmode=disable"
    volumes:
      - .:/album_manager
   # network_mode: "host"
    networks:
      - album_network
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - album_network
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
   mongodata:


networks:
   album_network: